version: "3"
services:
# ahora se indican los servicios por el orden en que se quiere que se inicien

#Por ejemplo, mongo debe estar antes de order.
#mongo: mismo nombre usado en el run.sh de Order y application.properties.
#Se resuelve en una dirección IP.
  mongo:
    image: yasinoff97/p1gps:db
    deploy:
      replicas: 1 #para escabilidad del servicio
      resources:
        limits:
          cpus: "0.15"
          memory: 200M
      restart_policy:
        condition: on-failure #reiniciar el contenedor si falla
    ports:
#mapeo el Puerto del contenedor (derecha) con el puerto
#del host del servicio (izquierda)
      - "28017:28017"
      - "27017:27017"
    volumes:
      - "db-data:/data/db" #para dar persistencia a la sesión
  order:
    image: yasinoff97/p1gps:order
    depends_on:
#le pasamos al servicio order la IP del servicio mongo
      - "mongo"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
  web:
    image: yasinoff97/p1gps:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"

volumes:
  db-data: